name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#server_docker
    - run: ./result | docker image load

    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Image'
      run: |
        docker image tag meshix-server:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-server:${{ github.event.release.tag_name }}
        docker push ghcr.io/code-growers/meshix/meshix-server:${{ github.event.release.tag_name }}
