name: "Stage"

on:
  push:
    branches:
      - 'main'

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: nix build .#server_docker
    - run: ./result | docker image load

    - run: nix build .#client_docker
    - run: docker load < ./result

    - run: nix build .#client_nix_docker
    - run: docker load < ./result
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Image'
      run: |
        # Tag
        docker image tag meshix-server:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-server:${{ github.sha }}
        docker image tag meshix-server:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-server:latest
        docker image tag meshix-client:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-client:${{ github.sha }}
        docker image tag meshix-client:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-client:latest
        docker image tag meshix-client-nix:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-client-nix:${{ github.sha }}
        docker image tag meshix-client-nix:0.0.1-rc0 ghcr.io/code-growers/meshix/meshix-client-nix:latest

        # Push
        docker push ghcr.io/code-growers/meshix/meshix-server:${{ github.sha }}
        docker push ghcr.io/code-growers/meshix/meshix-server:latest
        docker push ghcr.io/code-growers/meshix/meshix-client:${{ github.sha }}
        docker push ghcr.io/code-growers/meshix/meshix-client:latest
        docker push ghcr.io/code-growers/meshix/meshix-client-nix:${{ github.sha }}
        docker push ghcr.io/code-growers/meshix/meshix-client-nix:latest
